package com.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;

/**
 * This class is generated by Vaadin Designer and will be overwritten.
 * View shown after successful login
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class HomePage extends HorizontalLayout {
    protected Button menuButton;
    protected CssLayout menu;
    protected Button dashboard;
    protected Button reports;
    protected Button customize;
    protected Button logout;
    protected Label title;
    protected CssLayout content;
    protected CssLayout studentTable;

    public HomePage() {
        Design.read(this);
    }
}
